import EmbedPDF from 'https://cdn.jsdelivr.net/npm/@embedpdf/snippet@2/dist/embedpdf.js';
const input=document.getElementById('pdf-input');const dropZone=document.getElementById('drop-zone');const welcome=document.getElementById('welcome');const workspace=document.getElementById('workspace');const fileName=document.getElementById('file-name');const status=document.getElementById('status');const welcomeError=document.getElementById('welcome-error');const openAnother=document.getElementById('open-another');const downloadButton=document.getElementById('download-pdf');const addTextOptions=document.getElementById('add-text-options');const TRANSFER_DB='pdfmint-editor-transfer';const TRANSFER_STORE='uploads';const TRANSFER_KEY='pending-pdf';let objectUrl=null;let viewer=null;let registry=null;
function showWelcomeError(message){welcomeError.textContent=message;welcomeError.hidden=false}
function setStatus(message,state=''){status.className=`status sr-only ${state}`.trim();status.innerHTML=`<span class="spinner" aria-hidden="true"></span>${message}`}
function activateQuickTool(button){if(button.dataset.pendingTool){addTextOptions.hidden=true;setStatus(`${button.dataset.pendingTool} will be connected in a later integration.`,'ready');button.title=`${button.dataset.pendingTool} will be connected later`;return}if(!registry){setStatus('Quick tools are still loading…');return}try{const commands=registry.getPlugin('commands').provides();commands.execute(button.dataset.embedMode);commands.execute(button.dataset.embedCommand);document.querySelectorAll('.quick-tool').forEach(item=>item.setAttribute('aria-pressed',String(item===button)));addTextOptions.hidden=button.dataset.embedCommand!=='annotation:add-text';setStatus(`${button.textContent.trim()} selected`,'ready')}catch(error){console.error(error);setStatus(`${button.textContent.trim()} is not available for this document.`,'error-state')}}
function requestedQuickTool(){const tool=new URLSearchParams(location.search).get('tool');return{sign:'insert:add-signature',text:'annotation:add-text',image:'insert:add-image',highlight:'annotation:add-highlight'}[tool]||''}
function addTextApi(){return registry?.getPlugin('annotation')?.provides?.()||null}
function applyAddTextPatch(patch){const annotation=addTextApi();if(!annotation)return;try{annotation.setDefaults('free-text',patch);const selected=annotation.getSelected?.()||[];if(selected.some(item=>item.subtype==='free-text'||item.type==='freeText'||item.type==='FREETEXT'))annotation.updateSelection(patch)}catch(error){console.error('Could not update Add Text style:',error);setStatus('That text option is not available in this EmbedPDF build.','error-state')}}
function hideNativeEmbedPdfToolbars(viewerElement){const apply=()=>{const root=viewerElement.querySelector('embedpdf-container')?.shadowRoot;if(!root)return false;if(root.querySelector('#pdfbreeze-hide-native-toolbars'))return true;const style=document.createElement('style');style.id='pdfbreeze-hide-native-toolbars';style.textContent='.embedpdf-snippet-root>div>div.flex-col>div:not(.flex-1){display:none!important}';root.appendChild(style);return true};if(apply())return;const observer=new MutationObserver(()=>{if(apply())observer.disconnect()});observer.observe(viewerElement,{childList:true,subtree:true})}
async function openPdf(file){welcomeError.hidden=true;if(!file||(file.type!=='application/pdf'&&!file.name.toLowerCase().endsWith('.pdf'))){showWelcomeError('Please choose a PDF file.');return}if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=URL.createObjectURL(file);fileName.textContent=file.name;welcome.hidden=true;workspace.hidden=false;openAnother.hidden=false;setStatus('Loading editor…');const viewerElement=document.getElementById('pdf-viewer');try{viewer=EmbedPDF.init({type:'container',target:viewerElement,src:objectUrl,theme:{preference:'light',light:{accent:{primary:'#22a77b',primaryHover:'#178660',primaryActive:'#126b4e',primaryLight:'#eaf8f3',primaryForeground:'#ffffff'}}}});hideNativeEmbedPdfToolbars(viewerElement);registry=await viewer.registry;setStatus('Ready — edits stay in this browser','ready');downloadButton.hidden=false;const requested=requestedQuickTool();if(requested){const button=document.querySelector(`.quick-tool[data-embed-command="${requested}"]`);if(button)activateQuickTool(button)}}catch(error){console.error(error);setStatus('The test editor could not load. Please refresh and try again.','error-state')}}
function openTransferDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open(TRANSFER_DB,1);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains(TRANSFER_STORE))request.result.createObjectStore(TRANSFER_STORE)};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function takeTransferredPdf(){if(!window.indexedDB)return null;const db=await openTransferDb();const record=await new Promise((resolve,reject)=>{const tx=db.transaction(TRANSFER_STORE,'readwrite');const store=tx.objectStore(TRANSFER_STORE);const request=store.get(TRANSFER_KEY);request.onsuccess=()=>{const value=request.result||null;if(value)store.delete(TRANSFER_KEY);resolve(value)};request.onerror=()=>reject(request.error)});db.close();if(!record)return null;return new File([record.bytes],record.name,{type:record.type||'application/pdf',lastModified:record.lastModified||Date.now()})}
async function openPendingTransfer(){try{const file=await takeTransferredPdf();if(file)await openPdf(file)}catch(error){console.error('Could not open transferred PDF:',error);showWelcomeError('The transferred PDF could not be opened. Please choose it again.')}}
input.addEventListener('change',()=>openPdf(input.files[0]));for(const eventName of ['dragenter','dragover'])dropZone.addEventListener(eventName,event=>{event.preventDefault();dropZone.classList.add('is-dragging')});for(const eventName of ['dragleave','drop'])dropZone.addEventListener(eventName,event=>{event.preventDefault();dropZone.classList.remove('is-dragging')});dropZone.addEventListener('drop',event=>openPdf(event.dataTransfer.files[0]));openAnother.addEventListener('click',()=>window.location.reload());
document.querySelector('.quick-tools').addEventListener('click',event=>{const button=event.target.closest('.quick-tool');if(button)activateQuickTool(button)});
addTextOptions.addEventListener('input',event=>{const target=event.target;if(target.id==='add-text-opacity'){target.nextElementSibling.textContent=`${target.value}%`;applyAddTextPatch({opacity:Number(target.value)/100})}else if(target.id==='add-text-colour'){document.querySelector('.colour-preview-font').style.background=target.value;applyAddTextPatch({fontColor:target.value})}else if(target.id==='add-text-fill'){document.querySelector('.colour-preview-fill').style.background=target.value;applyAddTextPatch({interiorColor:target.value})}else if(target.id==='add-text-font'){applyAddTextPatch({fontFamily:target.value})}else if(target.id==='add-text-size'){applyAddTextPatch({fontSize:Number(target.value)})}});addTextOptions.addEventListener('click',event=>{const button=event.target.closest('.alignment-option');if(!button)return;addTextOptions.querySelectorAll('.alignment-option').forEach(item=>item.classList.toggle('active',item===button));applyAddTextPatch({textAlign:button.dataset.align})});
downloadButton.addEventListener('click',async()=>{if(!viewer)return;downloadButton.disabled=true;downloadButton.textContent='Preparing PDF…';setStatus('Preparing your edited PDF…');try{const registry=await viewer.registry;const exporter=registry.getPlugin('export').provides();await exporter.download();setStatus('Download ready','ready')}catch(error){console.error(error);setStatus('Download failed. Please try the editor download button.','error-state')}finally{downloadButton.disabled=false;downloadButton.textContent='Download PDF'}});window.addEventListener('beforeunload',()=>{if(objectUrl)URL.revokeObjectURL(objectUrl)});
openPendingTransfer();
