import EmbedPDF from 'https://cdn.jsdelivr.net/npm/@embedpdf/snippet@2/dist/embedpdf.js';
const input=document.getElementById('pdf-input');const dropZone=document.getElementById('drop-zone');const welcome=document.getElementById('welcome');const workspace=document.getElementById('workspace');const fileName=document.getElementById('file-name');const status=document.getElementById('status');const welcomeError=document.getElementById('welcome-error');const openAnother=document.getElementById('open-another');const downloadButton=document.getElementById('download-pdf');const TRANSFER_DB='pdfmint-editor-transfer';const TRANSFER_STORE='uploads';const TRANSFER_KEY='pending-pdf';let objectUrl=null;let viewer=null;let registry=null;
function showWelcomeError(message){welcomeError.textContent=message;welcomeError.hidden=false}
function setStatus(message,state=''){status.className=`status sr-only ${state}`.trim();status.innerHTML=`<span class="spinner" aria-hidden="true"></span>${message}`}
function activateQuickTool(button){if(button.dataset.pendingTool){setStatus(`${button.dataset.pendingTool} will be connected in a later integration.`,'ready');button.title=`${button.dataset.pendingTool} will be connected later`;return}if(!registry){setStatus('Quick tools are still loading…');return}try{const commands=registry.getPlugin('commands').provides();commands.execute(button.dataset.embedMode);commands.execute(button.dataset.embedCommand);document.querySelectorAll('.quick-tool').forEach(item=>item.setAttribute('aria-pressed',String(item===button)));setStatus(`${button.textContent.trim()} selected`,'ready')}catch(error){console.error(error);setStatus(`${button.textContent.trim()} is not available for this document.`,'error-state')}}
function requestedQuickTool(){const tool=new URLSearchParams(location.search).get('tool');return{sign:'insert:add-signature',text:'annotation:add-text',image:'insert:add-image',highlight:'annotation:add-highlight'}[tool]||''}
async function openPdf(file){welcomeError.hidden=true;if(!file||(file.type!=='application/pdf'&&!file.name.toLowerCase().endsWith('.pdf'))){showWelcomeError('Please choose a PDF file.');return}if(objectUrl)URL.revokeObjectURL(objectUrl);objectUrl=URL.createObjectURL(file);fileName.textContent=file.name;welcome.hidden=true;workspace.hidden=false;openAnother.hidden=false;setStatus('Loading editor…');try{viewer=EmbedPDF.init({type:'container',target:document.getElementById('pdf-viewer'),src:objectUrl,zoom:{defaultZoomLevel:1},theme:{preference:'light',light:{accent:{primary:'#22a77b',primaryHover:'#178660',primaryActive:'#126b4e',primaryLight:'#eaf8f3',primaryForeground:'#ffffff'}}}});registry=await viewer.registry;setStatus('Ready — edits stay in this browser','ready');downloadButton.hidden=false;const requested=requestedQuickTool();if(requested){const button=document.querySelector(`.quick-tool[data-embed-command="${requested}"]`);if(button)activateQuickTool(button)}}catch(error){console.error(error);setStatus('The test editor could not load. Please refresh and try again.','error-state')}}
function openTransferDb(){return new Promise((resolve,reject)=>{const request=indexedDB.open(TRANSFER_DB,1);request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains(TRANSFER_STORE))request.result.createObjectStore(TRANSFER_STORE)};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function takeTransferredPdf(){if(!window.indexedDB)return null;const db=await openTransferDb();const record=await new Promise((resolve,reject)=>{const tx=db.transaction(TRANSFER_STORE,'readwrite');const store=tx.objectStore(TRANSFER_STORE);const request=store.get(TRANSFER_KEY);request.onsuccess=()=>{const value=request.result||null;if(value)store.delete(TRANSFER_KEY);resolve(value)};request.onerror=()=>reject(request.error)});db.close();if(!record)return null;return new File([record.bytes],record.name,{type:record.type||'application/pdf',lastModified:record.lastModified||Date.now()})}
async function openPendingTransfer(){try{const file=await takeTransferredPdf();if(file)await openPdf(file)}catch(error){console.error('Could not open transferred PDF:',error);showWelcomeError('The transferred PDF could not be opened. Please choose it again.')}}
input.addEventListener('change',()=>openPdf(input.files[0]));for(const eventName of ['dragenter','dragover'])dropZone.addEventListener(eventName,event=>{event.preventDefault();dropZone.classList.add('is-dragging')});for(const eventName of ['dragleave','drop'])dropZone.addEventListener(eventName,event=>{event.preventDefault();dropZone.classList.remove('is-dragging')});dropZone.addEventListener('drop',event=>openPdf(event.dataTransfer.files[0]));openAnother.addEventListener('click',()=>window.location.reload());
document.querySelector('.quick-tools').addEventListener('click',event=>{const button=event.target.closest('.quick-tool');if(button)activateQuickTool(button)});
downloadButton.addEventListener('click',async()=>{if(!viewer)return;downloadButton.disabled=true;downloadButton.textContent='Preparing PDF…';setStatus('Preparing your edited PDF…');try{const registry=await viewer.registry;const exporter=registry.getPlugin('export').provides();await exporter.download();setStatus('Download ready','ready')}catch(error){console.error(error);setStatus('Download failed. Please try the editor download button.','error-state')}finally{downloadButton.disabled=false;downloadButton.textContent='Download PDF'}});window.addEventListener('beforeunload',()=>{if(objectUrl)URL.revokeObjectURL(objectUrl)});
openPendingTransfer();
