import EmbedPDF from 'https://cdn.jsdelivr.net/npm/@embedpdf/snippet@2/dist/embedpdf.js';
const input=document.getElementById('pdf-input');const dropZone=document.getElementById('drop-zone');const welcome=document.getElementById('welcome');const workspace=document.getElementById('workspace');const fileName=document.getElementById('file-name');const status=document.getElementById('status');const welcomeError=document.getElementById('welcome-error');const openAnother=document.getElementById('open-another');const downloadButton=document.getElementById('download-pdf');let objectUrl=null;let viewer=null;let registry=null;
function showWelcomeError(message){welcomeError.textContent=message;welcomeError.hidden=false}
function setStatus(message,state=''){status.className=`status ${state}`.trim();status.innerHTML=`<span class="spinner" aria-hidden="true"></span>${message}`}
function activateQuickTool(button){if(!registry){setStatus('Quick tools are still loading…');return}try{const commands=registry.getPlugin('commands').provides();commands.execute(button.dataset.embedMode);commands.execute(button.dataset.embedCommand);document.querySelectorAll('.quick-tool').forEach(item=>item.setAttribute('aria-pressed',String(item===button)));setStatus(`${button.textContent.trim()} selected`,'ready')}catch(error){console.error(error);setStatus(`${button.textContent.trim()} is not available for this document.`,'error-state')}}
async function openPdf(file){welcomeError.hidden=true;if(!file||(file.type!=='application/pdf'&&!file.name.toLowerCase().endsWith('.pdf'))){showWelcomeError('Please choose a PDF file.');return}objectUrl=URL.createObjectURL(file);fileName.textContent=file.name;welcome.hidden=true;workspace.hidden=false;openAnother.hidden=false;setStatus('Loading editor…');try{viewer=EmbedPDF.init({type:'container',target:document.getElementById('pdf-viewer'),src:objectUrl,theme:{preference:'light',light:{accent:{primary:'#22a77b',primaryHover:'#178660',primaryActive:'#126b4e',primaryLight:'#eaf8f3',primaryForeground:'#ffffff'}}}});registry=await viewer.registry;setStatus('Ready — edits stay in this browser','ready');downloadButton.hidden=false}catch(error){console.error(error);setStatus('The test editor could not load. Please refresh and try again.','error-state')}}
input.addEventListener('change',()=>openPdf(input.files[0]));for(const eventName of ['dragenter','dragover'])dropZone.addEventListener(eventName,event=>{event.preventDefault();dropZone.classList.add('is-dragging')});for(const eventName of ['dragleave','drop'])dropZone.addEventListener(eventName,event=>{event.preventDefault();dropZone.classList.remove('is-dragging')});dropZone.addEventListener('drop',event=>openPdf(event.dataTransfer.files[0]));openAnother.addEventListener('click',()=>window.location.reload());
document.querySelector('.quick-tools').addEventListener('click',event=>{const button=event.target.closest('.quick-tool');if(button)activateQuickTool(button)});
downloadButton.addEventListener('click',async()=>{if(!viewer)return;downloadButton.disabled=true;downloadButton.textContent='Preparing PDF…';setStatus('Preparing your edited PDF…');try{const registry=await viewer.registry;const exporter=registry.getPlugin('export').provides();await exporter.download();setStatus('Download ready','ready')}catch(error){console.error(error);setStatus('Download failed. Please try the editor download button.','error-state')}finally{downloadButton.disabled=false;downloadButton.textContent='Download PDF'}});window.addEventListener('beforeunload',()=>{if(objectUrl)URL.revokeObjectURL(objectUrl)});
